apiVersion: network.equinix.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/device
  labels:
    testing.upbound.io/example-name: csr1000v-ha
  name: csr1000v-ha
spec:
  forProvider:
    accountNumber: ${data.equinix_network_account.dc.number}
    coreCount: 2
    hostname: csr1000v-p
    metroCode: ${data.equinix_network_account.dc.metro_code}
    name: tf-csr1000v-p
    notifications:
    - john@equinix.com
    - marry@equinix.com
    - fred@equinix.com
    packageCode: SEC
    secondaryDevice:
    - accountNumber: ${data.equinix_network_account.sv.number}
      hostname: csr1000v-s
      metroCode: ${data.equinix_network_account.sv.metro_code}
      name: tf-csr1000v-s
      notifications:
      - john@equinix.com
      - marry@equinix.com
    termLength: 6
    throughput: 500
    throughputUnit: Mbps
    typeCode: CSR1000V
    version: 16.09.05

---

