apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    metro: sv
    name: tf-metal-to-azure
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    redundancy: redundant
    serviceTokenType: a_side
    speed: 1000Mbps
    type: shared

---

apiVersion: ecx.equinix.jet.crossplane.io/v1alpha1
kind: L2Connection
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    authorizationKey: ${azurerm_express_route_circuit.example.service_key}
    name: tf-metal-to-azure
    namedTag: PRIVATE
    notifications:
    - example@equinix.com
    profileUuidSelector:
      matchLabels:
        testing.upbound.io/example-name: equinix_ecx_l2_sellerprofile
    secondaryConnection:
    - name: tf-metal-to-azure-sec
      serviceToken: ${equinix_metal_connection.example.service_tokens.1.id}
    sellerMetroCode: AM
    serviceToken: ${equinix_metal_connection.example.service_tokens.0.id}
    speed: ${azurerm_express_route_circuit.example.bandwidth_in_mbps}
    speedUnit: MB

---

