apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: PortVlanAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/portvlanattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    deviceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test
    portName: eth1
    vlanVnid: ${equinix_metal_vlan.test.vxlan}

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/portvlanattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    billingCycle: hourly
    facilities:
    - ny5
    hostname: test
    operatingSystem: ubuntu_20_04
    plan: c3.small.x86
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Vlan
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/portvlanattachment
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: VLAN in New Jersey
    facility: ny5
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

