apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: VirtualCircuit
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/virtualcircuit
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    connectionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nniVlan: 1056
    portId: ${data.equinix_metal_connection.test.ports[0].id}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vlanIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Vlan
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/virtualcircuit
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    metro: ${data.equinix_metal_connection.test.metro}
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

