apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Vlan
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/vlan
  labels:
    testing.upbound.io/example-name: vlan1
  name: vlan1
spec:
  forProvider:
    description: VLAN in New Jersey
    facility: sv15
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

