apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  name: upjet-example
spec:
  forProvider:
    projectIdRef:
      name: upjet-example-project
    metro: da
    hostname: upjet-example
    plan: t3.small.x86
    operatingSystem: ubuntu_20_04
    billingCycle: hourly
    tags:
    - crossplane
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: upjet-example
    namespace: crossplane-system
