apiVersion: network.equinix.jet.crossplane.io/v1alpha1
kind: ACLTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/acltemplate
  labels:
    testing.upbound.io/example-name: myacl
  name: myacl
spec:
  forProvider:
    description: Test ACL template
    inboundRule:
    - description: inbound rule description
      dstPort: any
      protocol: IP
      srcPort: any
      subnet: 1.1.1.1/32
    - dstPort: 53,1045,2041
      protocol: UDP
      srcPort: any
      subnet: 172.16.25.0/24
    name: test
