/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *BGPSession) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Connection) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Device) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DeviceNetworkType) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Gateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *IPAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationMember) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Port) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PortVlanAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Project) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectAPIKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ProjectSSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReservedIPBlock) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SpotMarketRequest) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *SSHKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserAPIKey) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualCircuit) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vlan) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Vrf) Hub() {}
