apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: BGPSession
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/bgpsession
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    addressFamily: ipv4
    deviceId: ${equinix_metal_device.test.id}

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/bgpsession
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    billingCycle: hourly
    hostname: terraform-test-bgp-sesh
    metro:
    - ny
    operatingSystem: ubuntu_20_04
    plan: c3.small.x86
    projectId: ${local.project_id}

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: ReservedIPBlock
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/bgpsession
  labels:
    testing.upbound.io/example-name: addr
  name: addr
spec:
  forProvider:
    metro: ny
    projectId: ${local.project_id}
    quantity: 1
