apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    contactEmail: username@example.com
    metro: sv
    name: tf-metal-to-azure
    projectId: ${local.project_id}
    redundancy: redundant
    serviceTokenType: a_side
    speed: 1000Mbps
    type: shared

---

apiVersion: fabric.equinix.jet.crossplane.io/v1alpha1
kind: Connection
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/connection
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    authorization_key: ${azurerm_express_route_circuit.example.service_key}
    name: tf-metal-to-azure
    named_tag: PRIVATE
    notifications:
    - example@equinix.com
    profile_uuid: ${data.equinix_fabric_sellerprofile.example.uuid}
    secondary_connection:
    - name: tf-metal-to-azure-sec
      service_token: ${equinix_metal_connection.example.service_tokens.1.id}
    seller_metro_code: AM
    service_token: ${equinix_metal_connection.example.service_tokens.0.id}
    speed: ${azurerm_express_route_circuit.example.bandwidth_in_mbps}
    speed_unit: MB
