apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: ProjectSSHKey
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/projectsshkey
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
    projectId: ${local.project_id}
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDM/unxJeFqxsTJcu6mhqsMHSaVlpu+Jj/P+44zrm6X/MAoHSX3X9oLgujEjjZ74yLfdfe0bJrbL2YgJzNaEkIQQ1VPMHB5EhTKUBGnzlPP0hHTnxsjAm9qDHgUPgvgFDQSAMzdJRJ0Cexo16Ph9VxCoLh3dxiE7s2gaM2FdVg7P8aSxKypsxAhYV3D0AwqzoOyT6WWhBoQ0xZ85XevOTnJCpImSemEGs6nVGEsWcEc1d1YvdxFjAK4SdsKUMkj4Dsy/leKsdi/DEAf356vbMT1UHsXXvy5TlHu/Pa6qF53v32Enz+nhKy7/8W2Yt2yWx8HnQcT2rug9lvCXagJO6oauqRTO77C4QZn13ZLMZgLT66S/tNh2EX0gi6vmIs5dth8uF+K6nxIyKJXbcA4ASg7F1OJrHKFZdTc5v1cPeq6PcbqGgc+8SrPYQmzvQqLoMBuxyos2hUkYOmw3aeWJj9nFa8Wu5WaN89mUeOqSkU4S5cgUzWUOmKey56B/j/s1sVys9rMhZapVs0wL4L9GBBM48N5jAQZnnpo85A8KsZq5ME22bTLqnxsDXqDYZvS7PSI6Dxi7eleOFE/NYYDkrgDLHTQri8ucDMVeVWHgoMY2bPXdn7KKy5jW5jKsf8EPARXg77A4gRYmgKrcwIKqJEUPqyxJBe0CPoGTqgXPRsUiQ==
      tomk@hp2

---

apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: Device
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/projectsshkey
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    billingCycle: hourly
    hostname: test
    metro: ny
    operatingSystem: ubuntu_20_04
    plan: c3.medium.x86
    projectId: ${local.project_id}
    projectSshKeyIds:
    - ${equinix_metal_project_ssh_key.test.id}
