apiVersion: metal.equinix.jet.crossplane.io/v1alpha1
kind: UserAPIKey
metadata:
  annotations:
    meta.upbound.io/example-id: metal/v1alpha1/userapikey
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    description: Read-only user key
    readOnly: true
