/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by terrajet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ACLTemplateObservation struct {
	DeviceACLStatus *string `json:"deviceAclStatus,omitempty" tf:"device_acl_status,omitempty"`

	DeviceDetails []DeviceDetailsObservation `json:"deviceDetails,omitempty" tf:"device_details,omitempty"`

	DeviceID *string `json:"deviceId,omitempty" tf:"device_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InboundRule []InboundRuleObservation `json:"inboundRule,omitempty" tf:"inbound_rule,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type ACLTemplateParameters struct {

	// ACL template description, up to 200 characters
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// One or more rules to specify allowed inbound traffic. Rules are ordered, matching traffic rule stops processing subsequent ones.
	// +kubebuilder:validation:Required
	InboundRule []InboundRuleParameters `json:"inboundRule" tf:"inbound_rule,omitempty"`

	// ACL template location metro code
	// +kubebuilder:validation:Optional
	MetroCode *string `json:"metroCode,omitempty" tf:"metro_code,omitempty"`

	// ACL template name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`
}

type DeviceDetailsObservation struct {
	ACLStatus *string `json:"aclStatus,omitempty" tf:"acl_status,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	UUID *string `json:"uuid,omitempty" tf:"uuid,omitempty"`
}

type DeviceDetailsParameters struct {
}

type InboundRuleObservation struct {
	SequenceNumber *float64 `json:"sequenceNumber,omitempty" tf:"sequence_number,omitempty"`

	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type InboundRuleParameters struct {

	// Inbound rule description, up to 200 characters
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Inbound traffic destination ports. Either up to 10, comma separated ports or port range or any word
	// +kubebuilder:validation:Required
	DstPort *string `json:"dstPort" tf:"dst_port,omitempty"`

	// Inbound traffic protocol. One of: `IP`, `TCP`, `UDP`
	// +kubebuilder:validation:Required
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`

	// Inbound traffic source ports. Either up to 10, comma separated ports or port range or any word
	// +kubebuilder:validation:Required
	SrcPort *string `json:"srcPort" tf:"src_port,omitempty"`

	// Inbound traffic source IP subnet in CIDR format
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// Inbound traffic source IP subnets in CIDR format
	// +kubebuilder:validation:Optional
	Subnets []*string `json:"subnets,omitempty" tf:"subnets,omitempty"`
}

// ACLTemplateSpec defines the desired state of ACLTemplate
type ACLTemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ACLTemplateParameters `json:"forProvider"`
}

// ACLTemplateStatus defines the observed state of ACLTemplate.
type ACLTemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ACLTemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ACLTemplate is the Schema for the ACLTemplates API
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,equinixjet}
type ACLTemplate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ACLTemplateSpec   `json:"spec"`
	Status            ACLTemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ACLTemplateList contains a list of ACLTemplates
type ACLTemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ACLTemplate `json:"items"`
}

// Repository type metadata.
var (
	ACLTemplate_Kind             = "ACLTemplate"
	ACLTemplate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ACLTemplate_Kind}.String()
	ACLTemplate_KindAPIVersion   = ACLTemplate_Kind + "." + CRDGroupVersion.String()
	ACLTemplate_GroupVersionKind = CRDGroupVersion.WithKind(ACLTemplate_Kind)
)

func init() {
	SchemeBuilder.Register(&ACLTemplate{}, &ACLTemplateList{})
}
