//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalInfoObservation) DeepCopyInto(out *AdditionalInfoObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalInfoObservation.
func (in *AdditionalInfoObservation) DeepCopy() *AdditionalInfoObservation {
	if in == nil {
		return nil
	}
	out := new(AdditionalInfoObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalInfoParameters) DeepCopyInto(out *AdditionalInfoParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalInfoParameters.
func (in *AdditionalInfoParameters) DeepCopy() *AdditionalInfoParameters {
	if in == nil {
		return nil
	}
	out := new(AdditionalInfoParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesObservation) DeepCopyInto(out *FeaturesObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesObservation.
func (in *FeaturesObservation) DeepCopy() *FeaturesObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesParameters) DeepCopyInto(out *FeaturesParameters) {
	*out = *in
	if in.AllowRemoteConnections != nil {
		in, out := &in.AllowRemoteConnections, &out.AllowRemoteConnections
		*out = new(bool)
		**out = **in
	}
	if in.TestProfile != nil {
		in, out := &in.TestProfile, &out.TestProfile
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesParameters.
func (in *FeaturesParameters) DeepCopy() *FeaturesParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2Connection) DeepCopyInto(out *L2Connection) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2Connection.
func (in *L2Connection) DeepCopy() *L2Connection {
	if in == nil {
		return nil
	}
	out := new(L2Connection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2Connection) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepter) DeepCopyInto(out *L2ConnectionAccepter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepter.
func (in *L2ConnectionAccepter) DeepCopy() *L2ConnectionAccepter {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2ConnectionAccepter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepterList) DeepCopyInto(out *L2ConnectionAccepterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L2ConnectionAccepter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepterList.
func (in *L2ConnectionAccepterList) DeepCopy() *L2ConnectionAccepterList {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2ConnectionAccepterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepterObservation) DeepCopyInto(out *L2ConnectionAccepterObservation) {
	*out = *in
	if in.AwsConnectionID != nil {
		in, out := &in.AwsConnectionID, &out.AwsConnectionID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepterObservation.
func (in *L2ConnectionAccepterObservation) DeepCopy() *L2ConnectionAccepterObservation {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepterParameters) DeepCopyInto(out *L2ConnectionAccepterParameters) {
	*out = *in
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.AwsProfile != nil {
		in, out := &in.AwsProfile, &out.AwsProfile
		*out = new(string)
		**out = **in
	}
	if in.ConnectionID != nil {
		in, out := &in.ConnectionID, &out.ConnectionID
		*out = new(string)
		**out = **in
	}
	if in.SecretKeySecretRef != nil {
		in, out := &in.SecretKeySecretRef, &out.SecretKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepterParameters.
func (in *L2ConnectionAccepterParameters) DeepCopy() *L2ConnectionAccepterParameters {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepterSpec) DeepCopyInto(out *L2ConnectionAccepterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepterSpec.
func (in *L2ConnectionAccepterSpec) DeepCopy() *L2ConnectionAccepterSpec {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionAccepterStatus) DeepCopyInto(out *L2ConnectionAccepterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionAccepterStatus.
func (in *L2ConnectionAccepterStatus) DeepCopy() *L2ConnectionAccepterStatus {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionAccepterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionList) DeepCopyInto(out *L2ConnectionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L2Connection, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionList.
func (in *L2ConnectionList) DeepCopy() *L2ConnectionList {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2ConnectionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionObservation) DeepCopyInto(out *L2ConnectionObservation) {
	*out = *in
	if in.ProviderStatus != nil {
		in, out := &in.ProviderStatus, &out.ProviderStatus
		*out = new(string)
		**out = **in
	}
	if in.RedundancyType != nil {
		in, out := &in.RedundancyType, &out.RedundancyType
		*out = new(string)
		**out = **in
	}
	if in.RedundantUUID != nil {
		in, out := &in.RedundantUUID, &out.RedundantUUID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionObservation.
func (in *L2ConnectionObservation) DeepCopy() *L2ConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionParameters) DeepCopyInto(out *L2ConnectionParameters) {
	*out = *in
	if in.AdditionalInfo != nil {
		in, out := &in.AdditionalInfo, &out.AdditionalInfo
		*out = make([]AdditionalInfoParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthorizationKey != nil {
		in, out := &in.AuthorizationKey, &out.AuthorizationKey
		*out = new(string)
		**out = **in
	}
	if in.DeviceInterfaceID != nil {
		in, out := &in.DeviceInterfaceID, &out.DeviceInterfaceID
		*out = new(int64)
		**out = **in
	}
	if in.DeviceUUID != nil {
		in, out := &in.DeviceUUID, &out.DeviceUUID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NamedTag != nil {
		in, out := &in.NamedTag, &out.NamedTag
		*out = new(string)
		**out = **in
	}
	if in.Notifications != nil {
		in, out := &in.Notifications, &out.Notifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PortUUID != nil {
		in, out := &in.PortUUID, &out.PortUUID
		*out = new(string)
		**out = **in
	}
	if in.ProfileUUID != nil {
		in, out := &in.ProfileUUID, &out.ProfileUUID
		*out = new(string)
		**out = **in
	}
	if in.ProfileUUIDRef != nil {
		in, out := &in.ProfileUUIDRef, &out.ProfileUUIDRef
		*out = new(v1.Reference)
		**out = **in
	}
	if in.ProfileUUIDSelector != nil {
		in, out := &in.ProfileUUIDSelector, &out.ProfileUUIDSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PurchaseOrderNumber != nil {
		in, out := &in.PurchaseOrderNumber, &out.PurchaseOrderNumber
		*out = new(string)
		**out = **in
	}
	if in.SecondaryConnection != nil {
		in, out := &in.SecondaryConnection, &out.SecondaryConnection
		*out = make([]SecondaryConnectionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SellerMetroCode != nil {
		in, out := &in.SellerMetroCode, &out.SellerMetroCode
		*out = new(string)
		**out = **in
	}
	if in.SellerRegion != nil {
		in, out := &in.SellerRegion, &out.SellerRegion
		*out = new(string)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(int64)
		**out = **in
	}
	if in.SpeedUnit != nil {
		in, out := &in.SpeedUnit, &out.SpeedUnit
		*out = new(string)
		**out = **in
	}
	if in.VlanCtag != nil {
		in, out := &in.VlanCtag, &out.VlanCtag
		*out = new(int64)
		**out = **in
	}
	if in.VlanStag != nil {
		in, out := &in.VlanStag, &out.VlanStag
		*out = new(int64)
		**out = **in
	}
	if in.ZsidePortUUID != nil {
		in, out := &in.ZsidePortUUID, &out.ZsidePortUUID
		*out = new(string)
		**out = **in
	}
	if in.ZsideVlanCtag != nil {
		in, out := &in.ZsideVlanCtag, &out.ZsideVlanCtag
		*out = new(int64)
		**out = **in
	}
	if in.ZsideVlanStag != nil {
		in, out := &in.ZsideVlanStag, &out.ZsideVlanStag
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionParameters.
func (in *L2ConnectionParameters) DeepCopy() *L2ConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionSpec) DeepCopyInto(out *L2ConnectionSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionSpec.
func (in *L2ConnectionSpec) DeepCopy() *L2ConnectionSpec {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ConnectionStatus) DeepCopyInto(out *L2ConnectionStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ConnectionStatus.
func (in *L2ConnectionStatus) DeepCopy() *L2ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(L2ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2Serviceprofile) DeepCopyInto(out *L2Serviceprofile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2Serviceprofile.
func (in *L2Serviceprofile) DeepCopy() *L2Serviceprofile {
	if in == nil {
		return nil
	}
	out := new(L2Serviceprofile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2Serviceprofile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ServiceprofileList) DeepCopyInto(out *L2ServiceprofileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]L2Serviceprofile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ServiceprofileList.
func (in *L2ServiceprofileList) DeepCopy() *L2ServiceprofileList {
	if in == nil {
		return nil
	}
	out := new(L2ServiceprofileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *L2ServiceprofileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ServiceprofileObservation) DeepCopyInto(out *L2ServiceprofileObservation) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ServiceprofileObservation.
func (in *L2ServiceprofileObservation) DeepCopy() *L2ServiceprofileObservation {
	if in == nil {
		return nil
	}
	out := new(L2ServiceprofileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ServiceprofileParameters) DeepCopyInto(out *L2ServiceprofileParameters) {
	*out = *in
	if in.APIIntegration != nil {
		in, out := &in.APIIntegration, &out.APIIntegration
		*out = new(bool)
		**out = **in
	}
	if in.AuthkeyLabel != nil {
		in, out := &in.AuthkeyLabel, &out.AuthkeyLabel
		*out = new(string)
		**out = **in
	}
	if in.BandwidthAlertThreshold != nil {
		in, out := &in.BandwidthAlertThreshold, &out.BandwidthAlertThreshold
		*out = new(float64)
		**out = **in
	}
	if in.BandwidthThresholdNotifications != nil {
		in, out := &in.BandwidthThresholdNotifications, &out.BandwidthThresholdNotifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConnectionNameLabel != nil {
		in, out := &in.ConnectionNameLabel, &out.ConnectionNameLabel
		*out = new(string)
		**out = **in
	}
	if in.CtagLabel != nil {
		in, out := &in.CtagLabel, &out.CtagLabel
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EquinixManagedPortVlan != nil {
		in, out := &in.EquinixManagedPortVlan, &out.EquinixManagedPortVlan
		*out = new(bool)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeaturesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IntegrationID != nil {
		in, out := &in.IntegrationID, &out.IntegrationID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Oversubscription != nil {
		in, out := &in.Oversubscription, &out.Oversubscription
		*out = new(string)
		**out = **in
	}
	if in.OversubscriptionAllowed != nil {
		in, out := &in.OversubscriptionAllowed, &out.OversubscriptionAllowed
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = make([]PortParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.PrivateUserEmails != nil {
		in, out := &in.PrivateUserEmails, &out.PrivateUserEmails
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProfileStatuschangeNotifications != nil {
		in, out := &in.ProfileStatuschangeNotifications, &out.ProfileStatuschangeNotifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.RedundancyRequired != nil {
		in, out := &in.RedundancyRequired, &out.RedundancyRequired
		*out = new(bool)
		**out = **in
	}
	if in.SecondaryVlanFromPrimary != nil {
		in, out := &in.SecondaryVlanFromPrimary, &out.SecondaryVlanFromPrimary
		*out = new(bool)
		**out = **in
	}
	if in.ServicekeyAutogenerated != nil {
		in, out := &in.ServicekeyAutogenerated, &out.ServicekeyAutogenerated
		*out = new(bool)
		**out = **in
	}
	if in.SpeedBand != nil {
		in, out := &in.SpeedBand, &out.SpeedBand
		*out = make([]SpeedBandParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpeedCustomizationAllowed != nil {
		in, out := &in.SpeedCustomizationAllowed, &out.SpeedCustomizationAllowed
		*out = new(bool)
		**out = **in
	}
	if in.SpeedFromAPI != nil {
		in, out := &in.SpeedFromAPI, &out.SpeedFromAPI
		*out = new(bool)
		**out = **in
	}
	if in.TagType != nil {
		in, out := &in.TagType, &out.TagType
		*out = new(string)
		**out = **in
	}
	if in.VcStatuschangeNotifications != nil {
		in, out := &in.VcStatuschangeNotifications, &out.VcStatuschangeNotifications
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ServiceprofileParameters.
func (in *L2ServiceprofileParameters) DeepCopy() *L2ServiceprofileParameters {
	if in == nil {
		return nil
	}
	out := new(L2ServiceprofileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ServiceprofileSpec) DeepCopyInto(out *L2ServiceprofileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ServiceprofileSpec.
func (in *L2ServiceprofileSpec) DeepCopy() *L2ServiceprofileSpec {
	if in == nil {
		return nil
	}
	out := new(L2ServiceprofileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L2ServiceprofileStatus) DeepCopyInto(out *L2ServiceprofileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L2ServiceprofileStatus.
func (in *L2ServiceprofileStatus) DeepCopy() *L2ServiceprofileStatus {
	if in == nil {
		return nil
	}
	out := new(L2ServiceprofileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortObservation) DeepCopyInto(out *PortObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortObservation.
func (in *PortObservation) DeepCopy() *PortObservation {
	if in == nil {
		return nil
	}
	out := new(PortObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortParameters) DeepCopyInto(out *PortParameters) {
	*out = *in
	if in.MetroCode != nil {
		in, out := &in.MetroCode, &out.MetroCode
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortParameters.
func (in *PortParameters) DeepCopy() *PortParameters {
	if in == nil {
		return nil
	}
	out := new(PortParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryConnectionObservation) DeepCopyInto(out *SecondaryConnectionObservation) {
	*out = *in
	if in.ProviderStatus != nil {
		in, out := &in.ProviderStatus, &out.ProviderStatus
		*out = new(string)
		**out = **in
	}
	if in.RedundancyType != nil {
		in, out := &in.RedundancyType, &out.RedundancyType
		*out = new(string)
		**out = **in
	}
	if in.RedundantUUID != nil {
		in, out := &in.RedundantUUID, &out.RedundantUUID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.ZsidePortUUID != nil {
		in, out := &in.ZsidePortUUID, &out.ZsidePortUUID
		*out = new(string)
		**out = **in
	}
	if in.ZsideVlanCtag != nil {
		in, out := &in.ZsideVlanCtag, &out.ZsideVlanCtag
		*out = new(int64)
		**out = **in
	}
	if in.ZsideVlanStag != nil {
		in, out := &in.ZsideVlanStag, &out.ZsideVlanStag
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryConnectionObservation.
func (in *SecondaryConnectionObservation) DeepCopy() *SecondaryConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(SecondaryConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecondaryConnectionParameters) DeepCopyInto(out *SecondaryConnectionParameters) {
	*out = *in
	if in.AuthorizationKey != nil {
		in, out := &in.AuthorizationKey, &out.AuthorizationKey
		*out = new(string)
		**out = **in
	}
	if in.DeviceInterfaceID != nil {
		in, out := &in.DeviceInterfaceID, &out.DeviceInterfaceID
		*out = new(int64)
		**out = **in
	}
	if in.DeviceUUID != nil {
		in, out := &in.DeviceUUID, &out.DeviceUUID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PortUUID != nil {
		in, out := &in.PortUUID, &out.PortUUID
		*out = new(string)
		**out = **in
	}
	if in.ProfileUUID != nil {
		in, out := &in.ProfileUUID, &out.ProfileUUID
		*out = new(string)
		**out = **in
	}
	if in.SellerMetroCode != nil {
		in, out := &in.SellerMetroCode, &out.SellerMetroCode
		*out = new(string)
		**out = **in
	}
	if in.SellerRegion != nil {
		in, out := &in.SellerRegion, &out.SellerRegion
		*out = new(string)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(int64)
		**out = **in
	}
	if in.SpeedUnit != nil {
		in, out := &in.SpeedUnit, &out.SpeedUnit
		*out = new(string)
		**out = **in
	}
	if in.VlanCtag != nil {
		in, out := &in.VlanCtag, &out.VlanCtag
		*out = new(int64)
		**out = **in
	}
	if in.VlanStag != nil {
		in, out := &in.VlanStag, &out.VlanStag
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecondaryConnectionParameters.
func (in *SecondaryConnectionParameters) DeepCopy() *SecondaryConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(SecondaryConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpeedBandObservation) DeepCopyInto(out *SpeedBandObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpeedBandObservation.
func (in *SpeedBandObservation) DeepCopy() *SpeedBandObservation {
	if in == nil {
		return nil
	}
	out := new(SpeedBandObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpeedBandParameters) DeepCopyInto(out *SpeedBandParameters) {
	*out = *in
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(int64)
		**out = **in
	}
	if in.SpeedUnit != nil {
		in, out := &in.SpeedUnit, &out.SpeedUnit
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpeedBandParameters.
func (in *SpeedBandParameters) DeepCopy() *SpeedBandParameters {
	if in == nil {
		return nil
	}
	out := new(SpeedBandParameters)
	in.DeepCopyInto(out)
	return out
}
